// MY KEIBA LAB v17.1 - 枠色 + レース詳細ソート
// v34: 自前の常時イベント監視を停止し、central coordinator から必要時だけ実行。
(() => {
  if (typeof state === 'undefined' || window.__MYKEIBA_RACE_UI_V17__) return;
  window.__MYKEIBA_RACE_UI_V17__ = true;
  const SORT_LABELS={number:'馬番順',tenRank:'テン順位',agariRank:'上がり順位'};
  const num=v=>{if(window.MyKeibaDataV16?.toNumber)return window.MyKeibaDataV16.toNumber(v);if(v===''||v==null||String(v).trim()==='—')return null;const n=Number(v);return Number.isFinite(n)?n:null;};
  function frameNo(horseNo,fieldSize){const n=Number(horseNo),total=Number(fieldSize);if(!Number.isInteger(n)||n<1||!Number.isInteger(total)||total<1||n>total)return null;if(total<=8)return Math.min(n,8);if(total<=16){const single=16-total;if(n<=single)return n;return single+Math.ceil((n-single)/2);}const triple=total-16,double=8-triple,doubleH=double*2;if(n<=doubleH)return Math.ceil(n/2);return double+Math.ceil((n-doubleH)/3);}
  function raceFromDetail(){const first=document.querySelector('#v4DetailBody [data-v4-expand]');if(!first)return null;return(state.races||[]).find(r=>(r.horses||[]).some(h=>h.id===first.dataset.v4Expand))||null;}
  function rowsByHorse(table){const map=new Map();[...table.querySelectorAll('tbody > tr')].forEach(tr=>{if(tr.classList.contains('v4-horse-detail-row')){const id=tr.dataset.v4DetailRow;if(!id)return;if(!map.has(id))map.set(id,{});map.get(id).detail=tr;}else{const id=tr.querySelector('[data-v4-expand]')?.dataset.v4Expand;if(!id)return;if(!map.has(id))map.set(id,{});map.get(id).main=tr;}});return map;}
  function decorateFrameColors(table,race){const total=(race.horses||[]).length,rowMap=rowsByHorse(table);for(const horse of race.horses||[]){const cell=rowMap.get(horse.id)?.main?.children?.[0];if(!cell)continue;const waku=frameNo(num(horse.number),total);if(!waku)continue;cell.dataset.waku=String(waku);let chip=cell.querySelector('.v17-number-chip');if(!chip){chip=document.createElement('span');chip.className='v17-number-chip';cell.textContent='';cell.appendChild(chip);}chip.dataset.waku=String(waku);chip.textContent=horse.number||'—';}}
  function sortedHorses(race,mode){const list=[...(race.horses||[])];const value=h=>mode==='number'?num(h.number):num(h[mode]);return list.sort((a,b)=>{const av=value(a),bv=value(b);if(av==null&&bv==null)return(num(a.number)??999)-(num(b.number)??999);if(av==null)return 1;if(bv==null)return-1;return av-bv||(num(a.number)??999)-(num(b.number)??999);});}
  function applySort(table,race,mode){const tbody=table.tBodies?.[0];if(!tbody)return;const map=rowsByHorse(table),frag=document.createDocumentFragment();for(const h of sortedHorses(race,mode)){const p=map.get(h.id);if(p?.main)frag.appendChild(p.main);if(p?.detail)frag.appendChild(p.detail);}tbody.appendChild(frag);table.dataset.v17Sort=mode;document.querySelector('#v17SortBar')?.querySelectorAll('[data-v17-sort]').forEach(b=>b.classList.toggle('active',b.dataset.v17Sort===mode));}
  function installToolbar(body,table,race){let bar=body.querySelector('#v17SortBar');if(!bar){bar=document.createElement('div');bar.id='v17SortBar';bar.className='v17-sort-bar';bar.innerHTML=`<span class="v17-sort-label">並び替え</span><div class="v17-sort-buttons">${Object.entries(SORT_LABELS).map(([m,l])=>`<button type="button" data-v17-sort="${m}">${l}</button>`).join('')}</div><small>未取得「—」は下へ</small>`;const guide=body.querySelector('.v6-metric-guide'),wrap=table.closest('.v4-table-wrap');if(guide)guide.insertAdjacentElement('beforebegin',bar);else wrap?.insertAdjacentElement('beforebegin',bar);}bar.querySelectorAll('[data-v17-sort]').forEach(btn=>btn.onclick=()=>applySort(table,race,btn.dataset.v17Sort));}
  function decorate(){const body=document.querySelector('#v4DetailBody'),table=body?.querySelector('.v4-table');if(!body||!table)return false;const race=raceFromDetail();if(!race)return false;decorateFrameColors(table,race);installToolbar(body,table,race);if(!table.dataset.v17Init){table.dataset.v17Init='1';applySort(table,race,'number');}return true;}
  const style=document.createElement('style');style.textContent=`.v17-sort-bar{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:10px 0 8px;padding:9px 10px;border:1px solid #dfe7e2;border-radius:14px;background:#f8faf9}.v17-sort-buttons{display:flex;gap:6px;flex-wrap:wrap}.v17-sort-buttons button{border:1px solid #cfdad3;background:#fff;border-radius:999px;padding:7px 10px;font-weight:900}.v17-sort-buttons button.active{background:#183e2d;color:#fff}.v17-number-chip{display:inline-flex;align-items:center;justify-content:center;min-width:30px;height:30px;border-radius:6px;font-weight:950;border:1px solid rgba(0,0,0,.14)}.v17-number-chip[data-waku="1"]{background:#fff;color:#111}.v17-number-chip[data-waku="2"]{background:#191919;color:#fff}.v17-number-chip[data-waku="3"]{background:#d9363e;color:#fff}.v17-number-chip[data-waku="4"]{background:#2670c9;color:#fff}.v17-number-chip[data-waku="5"]{background:#f3cf2f;color:#111}.v17-number-chip[data-waku="6"]{background:#36a45c;color:#fff}.v17-number-chip[data-waku="7"]{background:#ef8a2d;color:#111}.v17-number-chip[data-waku="8"]{background:#ef9fbd;color:#111}`;document.head.appendChild(style);
  window.MyKeibaRaceUIV17={frameNo,applySort,decorate,decorateFrameColors};
})();